import streamlit as st

import hydralit_components as hc
import platform
import pandas as pd
import requests
import streamlit as st

# import streamlit_analytics
from navigation.model_for_DR import model_page
from navigation.using_modelDR import use_page
from navigation.results import result_page
from navigation.resources import resouces_page


import streamlit_lottie
import time
import json



from utils.components import footer_style, footer
try:
    from streamlit import rerun as rerun
except ImportError:
    # conditional import for streamlit version <1.27
    from streamlit import experimental_rerun as rerun

import os
horizontal_bar = "<hr style='margin-top: 0; margin-bottom: 0; height: 1px; border: 1px solid #749BC2;'><br>" 
horizontal_bar_big = "<hr style='margin-top: 0; margin-bottom: 0; height: 3px; border: 3px solid #749BC2;'><br>" 

def doctor_page():
    st.markdown("""
### Introduction

**Welcome to the Doctor's Portal:**

This portal is designed to provide healthcare professionals with comprehensive resources and tools for predicting Alzheimer's disease using MRI scans. Our advanced prediction model leverages cutting-edge technology to aid in early diagnosis and effective management of Alzheimer's disease. Here’s an overview of what you will find on this page:
""" ,unsafe_allow_html=True)
    
    c1,c2 = st.columns(2)

    c1.markdown("""
**Overview of the Prediction Model:**
- Learn about the sophisticated prediction model that analyzes MRI scans to identify biomarkers associated with Alzheimer's disease. Understand the data it uses, the accuracy of its predictions, and how it integrates into clinical practice.

**Interpretation of Results:**
- Gain insights on how to interpret the prediction results generated by the model. Understand what the different outcomes mean and explore the recommended next steps for patient care based on these results.
""" ,unsafe_allow_html=True)

    c2.markdown("""
**Integration with Clinical Practice:**
- Discover how the prediction model can be seamlessly incorporated into your clinical workflow. Learn about best practices for using the model to enhance diagnostic accuracy and guide treatment planning.

**Resources for Further Learning:**
- Access a curated selection of research papers, clinical guidelines, and educational materials to deepen your understanding of Alzheimer’s disease and the use of MRI in its prediction.
""" ,unsafe_allow_html=True)

    MODEL = "Overview of the Prediction Model"
    USE = "Use"
    RESULT = "Result"
    RESOURCES = "Resources"

    tabs =[ MODEL , USE , RESULT , RESOURCES]

    option_data =[
        {'icon': "⚙🔎", 'label': MODEL},
        {'icon': "🛠", 'label': USE},
        {'icon': "🥇", 'label': RESULT},
        {'icon': "🎯", 'label': RESOURCES},
    ]
    over_theme = {'txc_inactive': 'black', 'menu_background': '#D6E5FA', 'txc_active': 'white', 'option_active': '#749BC2'}
    font_fmt = {'font-class': 'h3', 'font-size': '50%'}

    chosen_tab =hc.option_bar(option_definition= option_data ,
                              title="",
                              key="SeconderyOption",
                              override_theme= over_theme,
                              horizontal_orientation= True)
    if chosen_tab == MODEL:
        model_page()

    if chosen_tab == USE:
        use_page()    

    if chosen_tab == RESULT: 
        result_page()  

    if chosen_tab == RESOURCES:
        resouces_page()            




